//! Portable scalar reference for the M1 opening-response projector.
//!
//! The closed-form projector and the direct physical enumerator intentionally
//! take different implementation paths.  Their common boundary is the
//! canonical `(response triple, matching-count vector)` key.

#![forbid(unsafe_code)]

mod carrier;
mod context;
mod m2;
pub mod m2_receipt;
mod projection;
mod receipt;
mod root;

pub use carrier::{
    ReducedOpeningCarrierV1, ReducedOpeningCoordinateV1, MAX_REDUCED_GRADE_V1,
    MAX_REDUCED_MATCHING_COUNT_V1, MIN_REDUCED_GRADE_V1,
};
pub use context::{
    OpeningContext, OpeningError, M1_DIRECT_WORLD_CAP_V1, MAX_GRADE, MAX_OPENING_MATCHING_COUNT_V1,
};
pub use m2::{
    ArithmeticNegativeControlV1, ArithmeticNegativeControlsV1, CheckedM2ProjectionPayloadV1,
    M2ArithmeticCorpusV1, M2BindingError, M2BoundOpeningTaskV1, M2BridgeError, M2CarrierArmV1,
    M2GlobalParityAccumulatorV1, M2GlobalParityDigestsV1, M2OpeningNegativeControlV1,
    M2OpeningNegativeControlsV1, M2OpeningParityCarrierV1, M2OpeningTaskV1, M2TaskKeyV1,
    OpeningChooseTableV1, PhysicalActionBindingV1, ReducedCarrierProfileV1,
    ReducedEvidenceBindingV1, ARITHMETIC_ABI_VERSION_V1, ARITHMETIC_CHECKED_UNDEFINED_V1,
    ARITHMETIC_HARD_BAD_ABI_V1, ARITHMETIC_HARD_BAD_EXPONENT_V1, ARITHMETIC_HARD_BAD_OPERAND_V1,
    ARITHMETIC_HARD_BAD_OPERATION_V1, ARITHMETIC_HARD_BAD_UNUSED_RHS_V1,
    ARITHMETIC_HARD_INTERNAL_V1, ARITHMETIC_INPUT_WORDS_V1, ARITHMETIC_NEGATIVE_CONTROL_COUNT_V1,
    ARITHMETIC_OP_CHECKED_ADD_V1, ARITHMETIC_OP_CHECKED_MUL_POW_420_V1,
    ARITHMETIC_OP_CHECKED_MUL_SMALL_V1, ARITHMETIC_OP_CHECKED_SUB_V1, ARITHMETIC_OP_COMPARE_V1,
    ARITHMETIC_OUTPUT_WORDS_V1, ARITHMETIC_SUCCESS_V1, M2_ARITHMETIC_CASE_COUNT_V1,
    M2_CONTEXT_TASK_COUNT_V1, M2_DIRECT_PARITY_COUNT_V1, M2_DIRECT_STOP_COUNT_V1,
    M2_PHYSICAL_BINDING_COUNT_V1, M2_POISON_WORD_V1, M2_REDUCED_BINDING_COUNT_V1,
    OPENING_ABI_VERSION_V1, OPENING_ARENA_SLOT_COUNT_V1, OPENING_CANDIDATE_SLOT_CAP_V1,
    OPENING_CHOOSE_DIM_V1, OPENING_CHOOSE_WORDS_V1, OPENING_HARD_BAD_ABI_V1,
    OPENING_HARD_BAD_COUNT_V1, OPENING_HARD_BAD_MASK_V1, OPENING_HARD_BAD_RESPONSE_ORDINAL_V1,
    OPENING_HARD_CHOOSE_INDEX_V1, OPENING_HARD_COEFFICIENT_OVERFLOW_V1,
    OPENING_HARD_MASS_OVERFLOW_V1, OPENING_HARD_SUPPORT_OVERFLOW_V1,
    OPENING_HARD_TOO_MANY_STRATA_V1, OPENING_MAX_CELL_COEFFICIENT_V1, OPENING_MAX_CELL_MASS_V1,
    OPENING_MAX_CELL_SUPPORT_V1, OPENING_MAX_CHOOSE_ENTRY_V1, OPENING_MAX_WHOLE_MASS_V1,
    OPENING_NEGATIVE_CONTROL_COUNT_V1, OPENING_SLOT_SKIP_V1, OPENING_SLOT_VALID_V1,
    OPENING_SLOT_WORDS_V1, OPENING_TASK_WORDS_V1,
};
pub use projection::{
    direct_preflight, project_closed_form, project_direct, DirectPreflightV1, OpeningCell,
    OpeningCellKey, OpeningProjection, OpeningResponseAggregate, ResponseRole,
    MAX_OPENING_CELLS_V1, OPENING_DEAL_COUNT,
};
pub use receipt::{
    canonical_m1_grade5_declared_stop_bytes_v1, canonical_opening_root_key_bytes_v1,
    validate_m1_grade5_declared_stop_v1, validate_opening_run_envelope_v1, BuildIdentityV1,
    OpeningEnvelopeError, VerifiedM1Grade5DeclaredStopV1, VerifiedOpeningEnvelopeV1,
    GPU_NATIVE_TRICK1_GUIDE_V02_SHA256, GT1_FREEZE_SET_DESCRIPTOR_V1, GT1_FREEZE_SET_SHA256_V1,
    M1_GRADE5_STOP_BUILD_IDENTITY_OFFSET, M1_GRADE5_STOP_HEADER_BYTES, M1_GRADE5_STOP_MAGIC,
    M1_GRADE5_STOP_REASON_DIRECT_WORLD_CAP_V1, M1_GRADE5_STOP_SEMANTIC_IDENTITY_SHA256_OFFSET,
    M1_GRADE5_STOP_VERSION, M1_GRADE5_STOP_WORLD_COUNT_V1, M1_INFO_NET_STATUS_NOT_APPLICABLE_V1,
    M1_INFO_NET_VERSION_NOT_APPLICABLE_V1, M1_OPENING_DIRECT_PARITY_TASK_ID_V1,
    M1_OPENING_PROJECTOR_TASK_ID_V1, OPENING_ENVELOPE_BUILD_IDENTITY_OFFSET,
    OPENING_ENVELOPE_HEADER_BYTES, OPENING_ENVELOPE_MAGIC, OPENING_ENVELOPE_ROOT_SHA256_OFFSET,
    OPENING_ENVELOPE_SEMANTIC_IDENTITY_SHA256_OFFSET, OPENING_ENVELOPE_VERSION,
    OPENING_RECEIPT_CELL_BYTES, OPENING_RECEIPT_HEADER_BYTES, OPENING_RECEIPT_MAGIC,
    OPENING_RECEIPT_VERSION, OPENING_ROOT_KEY_BYTES, OPENING_ROOT_KEY_MAGIC,
    OPENING_ROOT_KEY_VERSION,
};
pub use root::{
    DeclaringTeamMakesV1, IgnoreAuctionEvidenceV1, OpeningContractV1, OpeningModelProfileV1,
    OpeningRootV1, OpeningStraightHand21FieldActionsV1, PointBidV1,
    UniformCompatibleOpeningDealsV1, UniformRandomLegalV1, MAX_POINT_BID_V1, MIN_POINT_BID_V1,
    OPENING_MODEL_PROFILE_V1,
};
pub use walt_gpu_spec::{OpeningLikelihoodCoeff, ScaledOpeningMass, SupportCount};
