[package]
name = "walt-m2-runner"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
walt.workspace = true
walt-gpu-ref.workspace = true
walt-metal.workspace = true

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
float_arithmetic = "deny"
